[[redirects]]
  from = "/assets/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment] 
    RAZORPAY_KEY_ID = "rzp_live_UpMsxkW8VigT2x"
    RAZORPAY_KEY_SECRET = "E9nSHsZfdIeoPM7NnsMZJMbY"
    NEXT_PUBLIC_RAZORPAY_KEY_ID = "rzp_live_UpMsxkW8VigT2x"
    NEXT_PUBLIC_API_URL = "https://api.oneclickstays.com/api"
    BASEURL = "https://api.oneclickstays.com/api"
    MAPS_API_KEY = "AIzaSyAZ1mEJoQz5Dh3C7P8DTaQnt0sInmi0dlo"