const villas = [
    {
        name: "Amilla – Villa 5",
        url: "https://www.lohono.com/villas/maldives/maldives/amilla-4-bedroom-villa-residence-5?adult_count=2",
        images: [
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/04-4_Bedroom_Villa_Residences_-_Pristine_beach.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/02-4_Bedroom_Villa_Residences_-_Poolside.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/01-4_Bedroom_Villa_Residences_-Incredible_location.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/03-4_Bedroom_Villa_Residences_-_Relax_and_indulge_poolside.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/05-4_Bedroom_Villa_Residences_-_Luxe_living.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/06-4_Bedroom_Villa_Residences_-_Guest_bedroom_luxury.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/07-4_Bedroom_Villa_Residences_-Contemporary_bathroom.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/08-4_Bedroom_Villa_Residences_-_Perfection.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/09-4_Bedroom_Villa_Residences_-Terrace_view.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/10-4_Bedroom_Villa_Residences_-_Fun_watersports.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/11-4_Bedroom_Villa_Residences_-_Sail_in_natural_beauty.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/12-4_Bedroom_Villa_Residences_-_Evening_ambience.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/13-4_Bedroom_Villa_Residences_-Fabulous_sandpit_for_kids.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/14-4_Bedroom_Villa_Residences_-_Perfect_bath_in_the_spa.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/15-4_Bedroom_Villa_Residences_-_Amazing_walkway_to_the_spa_pavilion.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/16-4_Bedroom_Villa_Residences_-_Sail_with_the_wind.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/17-4_Bedroom_Villa_Residences_-_Exquisite_setting_to_rejuvenate.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/18-4_Bedroom_Villa_Residences_-_Relax_and_relish.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/19-4_Bedroom_Villa_Residences_-_Stately_palms.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-5/20-4_Bedroom_Villa_Residences_-_Buggies.jpg",
        ],
        description:
            "The six Amilla – 4 Bedroom Villa Residences are among only eight private residences in an elite gated community on this coral-fringed island resort in the Maldives’ Baa Atoll – a UNESCO biosphere reserve.  Think absolute beachfront location, crystal lagoons, pristine white sands, private pool, acres of living space and heart-warming service.  Then add the Amilla Fushi resort’s outstanding facilities: restaurants, spa, personal training, kids club, diving, big game fishing and water sports, pro tennis, football and many other activities.  This is “paradise – the most idyllic and relaxing place on earth”, says supermodel Kate Moss.  Can it get any better!",
        rules: [],
        amenities: [
            "Oven/Hotplates",
            "TV (Local channels)",
            "DVD Player",
            "Landline Phone (Local Calls)",
            "Internet (WiFi)",
            "Board Games/Toys",
            "Book Selection",
            "Ceiling Fans",
            "Iron/Board",
            "Main Dining (10 persons)",
            "Air-con",
            "Digital Film and Music Library",
            "DVD Library",
            "IDD (Extra)",
            "Printer (Extra)",
            "Fax (Extra)",
            "Mobile Phone (Local Calls)",
            "Laundry Service",
            "iPod",
            "Sauna (shared)",
            "Tennis Court (shared)",
            "Bicycles",
            "Bed Linen",
            "Towels",
            "Toiletries",
            "Equipped Kitchen",
            "Microwave",
            "BBQ",
            "Wine Fridge",
            "Coffee Machine",
            "TV (Satellite/Cable)",
            "iPod Dock/Speakers",
            "Hairdryers",
            "Table Tennis",
            "Gym (shared)",
            "Generator",
            "Safe",
            "Computer (Extra)",
            "Baby Cot",
            "Extra Bed (Roll away/mattress) (Extra)",
            "High Chairs",
            "Swimming Pool (Private)",
            "Car Parking",
            "Washing Machine",
            "Dish Washer",
        ],
        location: "Amilla Fushi, Baa Atoll, Male, Republic of Maldives 2123",
        price: 397375,
        capacity: ["Upto 8 Guests", "4 Bedrooms", "4 Bathrooms", "1 Pool"],
        _tm: 93500,
        _lr: 374000,
        _hr: 420750,
        vendor: "Lohono Stays",
        guests: 8,
        bedrooms: 4,
        rating: "4.5",
        reveiws: 14082,
    },
    {
        name: "Amilla – Villa 3",
        url: "https://www.lohono.com/villas/maldives/maldives/amilla-4-bedroom-villa-residence-3?adult_count=2",
        images: [
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/02-4_Bedroom_Villa_Residences_-_Poolside.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/01-4_Bedroom_Villa_Residences_-Incredible_location.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/03-4_Bedroom_Villa_Residences_-_Relax_and_indulge_poolside.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/04-4_Bedroom_Villa_Residences_-_Pristine_beach.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/05-4_Bedroom_Villa_Residences_-_Luxe_living.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/06-4_Bedroom_Villa_Residences_-_Guest_bedroom_luxury.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/07-4_Bedroom_Villa_Residences_-Contemporary_bathroom.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/08-4_Bedroom_Villa_Residences_-_Perfection.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/09-4_Bedroom_Villa_Residences_-Terrace_view.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/10-4_Bedroom_Villa_Residences_-_Fun_watersports.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/11-4_Bedroom_Villa_Residences_-_Sail_in_natural_beauty.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/12-4_Bedroom_Villa_Residences_-_Evening_ambience.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/13-4_Bedroom_Villa_Residences_-Fabulous_sandpit_for_kids.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/14-4_Bedroom_Villa_Residences_-_Perfect_bath_in_the_spa.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/15-4_Bedroom_Villa_Residences_-_Amazing_walkway_to_the_spa_pavilion.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/16-4_Bedroom_Villa_Residences_-_Sail_with_the_wind.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/17-4_Bedroom_Villa_Residences_-_Exquisite_setting_to_rejuvenate.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/18-4_Bedroom_Villa_Residences_-_Relax_and_relish.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/19-4_Bedroom_Villa_Residences_-_Stately_palms.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-3/20-4_Bedroom_Villa_Residences_-_Buggies.jpg",
        ],
        description:
            "The six Amilla – 4 Bedroom Villa Residences are among only eight private residences in an elite gated community on this coral-fringed island resort in the Maldives’ Baa Atoll – a UNESCO biosphere reserve.  Think absolute beachfront location, crystal lagoons, pristine white sands, private pool, acres of living space and heart-warming service.  Then add the Amilla Fushi resort’s outstanding facilities: restaurants, spa, personal training, kids club, diving, big game fishing and water sports, pro tennis, football and many other activities.  This is “paradise – the most idyllic and relaxing place on earth”, says supermodel Kate Moss.  Can it get any better!",
        rules: [],
        amenities: [
            "Oven/Hotplates",
            "TV (Local channels)",
            "DVD Player",
            "Landline Phone (Local Calls)",
            "Internet (WiFi)",
            "Board Games/Toys",
            "Book Selection",
            "Ceiling Fans",
            "Iron/Board",
            "Main Dining (10 persons)",
            "Air-con",
            "Digital Film and Music Library",
            "DVD Library",
            "IDD (Extra)",
            "Printer (Extra)",
            "Fax (Extra)",
            "Mobile Phone (Local Calls)",
            "Laundry Service",
            "iPod",
            "Sauna (shared)",
            "Tennis Court (shared)",
            "Bicycles",
            "Dish Washer",
            "Bed Linen",
            "Towels",
            "Toiletries",
            "Equipped Kitchen",
            "Microwave",
            "BBQ",
            "Wine Fridge",
            "Coffee Machine",
            "TV (Satellite/Cable)",
            "iPod Dock/Speakers",
            "Hairdryers",
            "Table Tennis",
            "Gym (shared)",
            "Generator",
            "Safe",
            "Computer (Extra)",
            "Baby Cot",
            "Extra Bed (Roll away/mattress) (Extra)",
            "High Chairs",
            "Swimming Pool (Private)",
            "Car Parking",
            "Washing Machine",
        ],
        location: "Amilla Fushi, Baa Atoll, Male, Republic of Maldives 2123",
        price: 397375,
        capacity: ["Upto 8 Guests", "4 Bedrooms", "4 Bathrooms", "1 Pool"],
        _tm: 93500,
        _lr: 374000,
        _hr: 420750,
        vendor: "Lohono Stays",
        guests: 8,
        bedrooms: 4,
        rating: "4.8",
        reveiws: 6884,
    },
    {
        name: "Amilla – Villa 1",
        url: "https://www.lohono.com/villas/maldives/maldives/amilla-4-bedroom-villa-residence-1?adult_count=2",
        images: [
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/01-4_Bedroom_Villa_Residences_-Incredible_location.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/02-4_Bedroom_Villa_Residences_-_Poolside.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/03-4_Bedroom_Villa_Residences_-_Relax_and_indulge_poolside.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/04-4_Bedroom_Villa_Residences_-_Pristine_beach.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/05-4_Bedroom_Villa_Residences_-_Luxe_living.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/06-4_Bedroom_Villa_Residences_-_Guest_bedroom_luxury.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/07-4_Bedroom_Villa_Residences_-Contemporary_bathroom.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/08-4_Bedroom_Villa_Residences_-_Perfection.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/09-4_Bedroom_Villa_Residences_-Terrace_view.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/10-4_Bedroom_Villa_Residences_-_Fun_watersports.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/11-4_Bedroom_Villa_Residences_-_Sail_in_natural_beauty.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/12-4_Bedroom_Villa_Residences_-_Evening_ambience.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/13-4_Bedroom_Villa_Residences_-Fabulous_sandpit_for_kids.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/14-4_Bedroom_Villa_Residences_-_Perfect_bath_in_the_spa.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/15-4_Bedroom_Villa_Residences_-_Amazing_walkway_to_the_spa_pavilion.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/16-4_Bedroom_Villa_Residences_-_Sail_with_the_wind.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/17-4_Bedroom_Villa_Residences_-_Exquisite_setting_to_rejuvenate.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/18-4_Bedroom_Villa_Residences_-_Relax_and_relish.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/19-4_Bedroom_Villa_Residences_-_Stately_palms.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-1/20-4_Bedroom_Villa_Residences_-_Buggies.jpg",
        ],
        description:
            "The six Amilla – 4 Bedroom Villa Residences are among only eight private residences in an elite gated community on this coral-fringed island resort in the Maldives’ Baa Atoll – a UNESCO biosphere reserve. Think absolute beachfront location, crystal lagoons, pristine white sands, private pool, acres of living space and heart-warming service. Then add the Amilla Fushi resort’s outstanding facilities: restaurants, spa, personal training, kids club, diving, big game fishing and water sports, pro tennis, football and many other activities. This is “paradise – the most idyllic and relaxing place on earth”, says supermodel Kate Moss. Can it get any better!",
        rules: [],
        amenities: [
            "Oven/Hotplates",
            "TV (Local channels)",
            "DVD Player",
            "Landline Phone (Local Calls)",
            "Internet (WiFi)",
            "Board Games/Toys",
            "Book Selection",
            "Ceiling Fans",
            "Iron/Board",
            "Private Entrance",
            "Main Dining (10 persons)",
            "Air-con",
            "Digital Film and Music Library",
            "DVD Library",
            "IDD (Extra)",
            "Printer (Extra)",
            "Fax (Extra)",
            "Mobile Phone (Local Calls)",
            "Laundry Service",
            "iPod",
            "Sauna (shared)",
            "Tennis Court (shared)",
            "Bicycles",
            "Carbon Monoxide Detector",
            "Bed Linen",
            "Towels",
            "Toiletries",
            "Equipped Kitchen",
            "Microwave",
            "BBQ",
            "Wine Fridge",
            "Coffee Machine",
            "TV (Satellite/Cable)",
            "iPod Dock/Speakers",
            "Hairdryers",
            "Table Tennis",
            "Gym (shared)",
            "Generator",
            "Safe",
            "Computer (Extra)",
            "Baby Cot",
            "High Chairs",
            "Extra Bed (Roll away/mattress) (Extra)",
            "First Aid Kit",
            "Smoke Detector",
            "Swimming Pool (Private)",
            "Car Parking",
            "Washing Machine",
            "Dish Washer",
        ],
        location: "Amilla Fushi, Baa Atoll, Male, Republic of Maldives 2123",
        price: 397375,
        capacity: ["Upto 8 Guests", "4 Bedrooms", "4 Bathrooms", "1 Pool"],
        _tm: 93500,
        _lr: 374000,
        _hr: 420750,
        vendor: "Lohono Stays",
        guests: 8,
        bedrooms: 4,
        rating: "4.4",
        reveiws: 10154,
    },
    {
        name: "Amilla – Villa 2",
        url: "https://www.lohono.com/villas/maldives/maldives/amilla-4-bedroom-villa-residence-2?adult_count=2",
        images: [
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/03-4_Bedroom_Villa_Residences_-_Relax_and_indulge_poolside.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/02-4_Bedroom_Villa_Residences_-_Poolside.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/01-4_Bedroom_Villa_Residences_-Incredible_location.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/04-4_Bedroom_Villa_Residences_-_Pristine_beach.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/05-4_Bedroom_Villa_Residences_-_Luxe_living.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/06-4_Bedroom_Villa_Residences_-_Guest_bedroom_luxury.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/07-4_Bedroom_Villa_Residences_-Contemporary_bathroom.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/08-4_Bedroom_Villa_Residences_-_Perfection.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/09-4_Bedroom_Villa_Residences_-Terrace_view.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/10-4_Bedroom_Villa_Residences_-_Fun_watersports.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/11-4_Bedroom_Villa_Residences_-_Sail_in_natural_beauty.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/12-4_Bedroom_Villa_Residences_-_Evening_ambience.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/13-4_Bedroom_Villa_Residences_-Fabulous_sandpit_for_kids.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/14-4_Bedroom_Villa_Residences_-_Perfect_bath_in_the_spa.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/15-4_Bedroom_Villa_Residences_-_Amazing_walkway_to_the_spa_pavilion.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/16-4_Bedroom_Villa_Residences_-_Sail_with_the_wind.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/17-4_Bedroom_Villa_Residences_-_Exquisite_setting_to_rejuvenate.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/18-4_Bedroom_Villa_Residences_-_Relax_and_relish.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/19-4_Bedroom_Villa_Residences_-_Stately_palms.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-2/20-4_Bedroom_Villa_Residences_-_Buggies.jpg",
        ],
        description:
            "The six Amilla – 4 Bedroom Villa Residences are among only eight private residences in an elite gated community on this coral-fringed island resort in the Maldives’ Baa Atoll – a UNESCO biosphere reserve.  Think absolute beachfront location, crystal lagoons, pristine white sands, private pool, acres of living space and heart-warming service.  Then add the Amilla Fushi resort’s outstanding facilities: restaurants, spa, personal training, kids club, diving, big game fishing and water sports, pro tennis, football and many other activities.  This is “paradise – the most idyllic and relaxing place on earth”, says supermodel Kate Moss.  Can it get any better!",
        rules: [],
        amenities: [
            "Oven/Hotplates",
            "TV (Local channels)",
            "DVD Player",
            "Landline Phone (Local Calls)",
            "Internet (WiFi)",
            "Board Games/Toys",
            "Book Selection",
            "Ceiling Fans",
            "Iron/Board",
            "Main Dining (10 persons)",
            "Air-con",
            "Digital Film and Music Library",
            "DVD Library",
            "IDD (Extra)",
            "Printer (Extra)",
            "Fax (Extra)",
            "Mobile Phone (Local Calls)",
            "Laundry Service",
            "iPod",
            "Sauna (shared)",
            "Tennis Court (shared)",
            "Bicycles",
            "Dish Washer",
            "Bed Linen",
            "Towels",
            "Toiletries",
            "Equipped Kitchen",
            "Microwave",
            "BBQ",
            "Wine Fridge",
            "Coffee Machine",
            "TV (Satellite/Cable)",
            "iPod Dock/Speakers",
            "Hairdryers",
            "Table Tennis",
            "Gym (shared)",
            "Generator",
            "Safe",
            "Computer (Extra)",
            "Baby Cot",
            "Extra Bed (Roll away/mattress) (Extra)",
            "High Chairs",
            "Swimming Pool (Private)",
            "Car Parking",
            "Washing Machine",
        ],
        location: "Amilla Fushi, Baa Atoll, Male, Republic of Maldives 2123",
        price: 397375,
        capacity: ["Upto 8 Guests", "4 Bedrooms", "4 Bathrooms", "1 Pool"],
        _tm: 93500,
        _lr: 374000,
        _hr: 420750,
        vendor: "Lohono Stays",
        guests: 8,
        bedrooms: 4,
        rating: "4.4",
        reveiws: 836,
    },
    {
        name: "Amilla – Villa 4",
        url: "https://www.lohono.com/villas/maldives/maldives/amilla-4-bedroom-villa-residence-4?adult_count=2",
        images: [
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/06-4_Bedroom_Villa_Residences_-_Guest_bedroom_luxury.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/02-4_Bedroom_Villa_Residences_-_Poolside.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/03-4_Bedroom_Villa_Residences_-_Relax_and_indulge_poolside.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/04-4_Bedroom_Villa_Residences_-_Pristine_beach.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/05-4_Bedroom_Villa_Residences_-_Luxe_living.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/01-4_Bedroom_Villa_Residences_-Incredible_location.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/07-4_Bedroom_Villa_Residences_-Contemporary_bathroom.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/08-4_Bedroom_Villa_Residences_-_Perfection.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/09-4_Bedroom_Villa_Residences_-Terrace_view.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/10-4_Bedroom_Villa_Residences_-_Fun_watersports.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/11-4_Bedroom_Villa_Residences_-_Sail_in_natural_beauty.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/12-4_Bedroom_Villa_Residences_-_Evening_ambience.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/13-4_Bedroom_Villa_Residences_-Fabulous_sandpit_for_kids.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/14-4_Bedroom_Villa_Residences_-_Perfect_bath_in_the_spa.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/15-4_Bedroom_Villa_Residences_-_Amazing_walkway_to_the_spa_pavilion.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/16-4_Bedroom_Villa_Residences_-_Sail_with_the_wind.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/17-4_Bedroom_Villa_Residences_-_Exquisite_setting_to_rejuvenate.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/18-4_Bedroom_Villa_Residences_-_Relax_and_relish.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/19-4_Bedroom_Villa_Residences_-_Stately_palms.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-4/20-4_Bedroom_Villa_Residences_-_Buggies.jpg",
        ],
        description:
            "The six Amilla – 4 Bedroom Villa Residences are among only eight private residences in an elite gated community on this coral-fringed island resort in the Maldives’ Baa Atoll – a UNESCO biosphere reserve.  Think absolute beachfront location, crystal lagoons, pristine white sands, private pool, acres of living space and heart-warming service.  Then add the Amilla Fushi resort’s outstanding facilities: restaurants, spa, personal training, kids club, diving, big game fishing and water sports, pro tennis, football and many other activities.  This is “paradise – the most idyllic and relaxing place on earth”, says supermodel Kate Moss.  Can it get any better!",
        rules: [],
        amenities: [
            "Oven/Hotplates",
            "TV (Local channels)",
            "DVD Player",
            "Landline Phone (Local Calls)",
            "Internet (WiFi)",
            "Board Games/Toys",
            "Book Selection",
            "Ceiling Fans",
            "Iron/Board",
            "High Chairs (Extra)",
            "Air-con",
            "Digital Film and Music Library",
            "DVD Library",
            "IDD (Extra)",
            "Printer (Extra)",
            "Fax (Extra)",
            "Mobile Phone (Local Calls)",
            "Laundry Service",
            "iPod",
            "Sauna (shared)",
            "Tennis Court (shared)",
            "Bicycles",
            "Main Dining (10 persons) (Extra)",
            "Towels",
            "Toiletries",
            "Equipped Kitchen",
            "Microwave",
            "BBQ",
            "Wine Fridge",
            "Coffee Machine",
            "TV (Satellite/Cable)",
            "iPod Dock/Speakers",
            "Hairdryers",
            "Table Tennis",
            "Gym (shared)",
            "Generator",
            "Safe",
            "Computer (Extra)",
            "Baby Cot",
            "Extra Bed (Roll away/mattress) (Extra)",
            "Swimming Pool (Private)",
            "Car Parking",
            "Washing Machine",
            "Dish Washer",
            "Bed Linen",
        ],
        location: "Amilla Fushi, Baa Atoll, Male, Republic of Maldives 2123",
        price: 397375,
        capacity: ["Upto 8 Guests", "4 Bedrooms", "4 Bathrooms", "1 Pool"],
        _tm: 93500,
        _lr: 374000,
        _hr: 420750,
        vendor: "Lohono Stays",
        guests: 8,
        bedrooms: 4,
        rating: "4.7",
        reveiws: 7778,
    },
    {
        name: "Amilla – Villa 6",
        url: "https://www.lohono.com/villas/maldives/maldives/amilla-4-bedroom-villa-residence-6?adult_count=2",
        images: [
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/08-4_Bedroom_Villa_Residences_-_Perfection.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/02-4_Bedroom_Villa_Residences_-_Poolside.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/03-4_Bedroom_Villa_Residences_-_Relax_and_indulge_poolside.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/04-4_Bedroom_Villa_Residences_-_Pristine_beach.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/05-4_Bedroom_Villa_Residences_-_Luxe_living.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/06-4_Bedroom_Villa_Residences_-_Guest_bedroom_luxury.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/07-4_Bedroom_Villa_Residences_-Contemporary_bathroom.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/01-4_Bedroom_Villa_Residences_-Incredible_location.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/09-4_Bedroom_Villa_Residences_-Terrace_view.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/10-4_Bedroom_Villa_Residences_-_Fun_watersports.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/11-4_Bedroom_Villa_Residences_-_Sail_in_natural_beauty.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/12-4_Bedroom_Villa_Residences_-_Evening_ambience.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/13-4_Bedroom_Villa_Residences_-Fabulous_sandpit_for_kids.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/14-4_Bedroom_Villa_Residences_-_Perfect_bath_in_the_spa.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/15-4_Bedroom_Villa_Residences_-_Amazing_walkway_to_the_spa_pavilion.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/16-4_Bedroom_Villa_Residences_-_Sail_with_the_wind.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/17-4_Bedroom_Villa_Residences_-_Exquisite_setting_to_rejuvenate.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/18-4_Bedroom_Villa_Residences_-_Relax_and_relish.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/19-4_Bedroom_Villa_Residences_-_Stately_palms.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-4-bedroom-villa-residence-6/20-4_Bedroom_Villa_Residences_-_Buggies.jpg",
        ],
        description:
            "The six Amilla – 4 Bedroom Villa Residences are among only eight private residences in an elite gated community on this coral-fringed island resort in the Maldives’ Baa Atoll – a UNESCO biosphere reserve.  Think absolute beachfront location, crystal lagoons, pristine white sands, private pool, acres of living space and heart-warming service.  Then add the Amilla Fushi resort’s outstanding facilities: restaurants, spa, personal training, kids club, diving, big game fishing and water sports, pro tennis, football and many other activities.  This is “paradise – the most idyllic and relaxing place on earth”, says supermodel Kate Moss.  Can it get any better!",
        rules: [],
        amenities: [
            "Oven/Hotplates",
            "TV (Local channels)",
            "DVD Player",
            "Landline Phone (Local Calls)",
            "Internet (WiFi)",
            "Board Games/Toys",
            "Book Selection",
            "Ceiling Fans",
            "Iron/Board",
            "Main Dining (10 persons)",
            "Air-con",
            "Digital Film and Music Library",
            "DVD Library",
            "IDD (Extra)",
            "Printer (Extra)",
            "Fax (Extra)",
            "Mobile Phone (Local Calls)",
            "Laundry Service",
            "iPod",
            "Sauna (shared)",
            "Tennis Court (shared)",
            "Bicycles",
            "Washing Machine",
            "Dish Washer",
            "Bed Linen",
            "Towels",
            "Toiletries",
            "Equipped Kitchen",
            "Microwave",
            "BBQ",
            "Wine Fridge",
            "Coffee Machine",
            "TV (Satellite/Cable)",
            "iPod Dock/Speakers",
            "Hairdryers",
            "Table Tennis",
            "Gym (shared)",
            "Generator",
            "Safe",
            "Computer (Extra)",
            "Baby Cot",
            "Extra Bed (Roll away/mattress) (Extra)",
            "High Chairs",
            "Swimming Pool (Private)",
            "Car Parking",
        ],
        location: "Amilla Fushi, Baa Atoll, Male, Republic of Maldives 2123",
        price: 397375,
        capacity: ["Upto 8 Guests", "4 Bedrooms", "4 Bathrooms", "1 Pool"],
        _tm: 93500,
        _lr: 374000,
        _hr: 420750,
        vendor: "Lohono Stays",
        guests: 8,
        bedrooms: 4,
        rating: "3.9",
        reveiws: 9284,
    },
    {
        name: "Amilla – The Great Beach Villa",
        url: "https://www.lohono.com/villas/maldives/maldives/amilla-the-great-beach-villa-residence?adult_count=2",
        images: [
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/1._The_Great_Beach_Villa_Residence_-_Modern_edge.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/2._The_Great_Beach_Villa_Residences_-_Stately_palms.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/3._The_Great_Beach_Villa_Residence_-_Absolute_perfection.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/4._The_Great_Beach_Villa_Residence_-_Dining_style.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/5._The_Great_Beach_Villa_Residence_-_The_ultimate_dining_setting.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/6._The_Great_Beach_Villa_Residence_-_Living_area.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/7._The_Great_Beach_Villa_Residence_-_Guest_bedroom_luxury.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/8._The_Great_Beach_Villa_Residence_-_Bedroom_Residence.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/9._The_Great_Beach_Villa_Residence_-_Ensuite_designer_style.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/10._The_Great_Beach_Villa_Residences_-_Tennis_games_for_two.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/11._The_Great_Beach_Villa_Residence_-_Incredible_entertaining_spaces.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/12._The_Great_Beach_Villa_Residence_-_Exceptional_personal_service.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/13._The_Great_Beach_Villa_Residence_-_Living_spaces.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/14._The_Great_Beach_Villa_Residence_-_Guest_bedroom_evening_feel.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/15._The_Great_Beach_Villa_Residence_-_Luxurious_living_spaces.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/16._The_Great_Beach_Villa_Residence_-_Modern_grandeur.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/17._The_Great_Beach_Villa_Residence_-_Bedroom_Residence.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/18._The_Great_Beach_Villa_Residence_-_Fabulous_sandpit_for_kids.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/19._The_Great_Beach_Villa_Residence_-_Fun_watersports.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-great-beach-villa-residence/20._The_Great_Beach_Villa_Residence_-_Windsailing_on_the_crystal-clear_water.jpg",
        ],
        description:
            "The Great Beach Villa Residence at Amilla is the largest of eight private residences in an elite gated community on this coral-fringed island resort in the Maldives’ Baa Atoli – a UNESCO biosphere reserve.  Think eight luxurious bedrooms, absolute beachfront location, crystal lagoons, pristine white sands, private pool, acres of living space and heart-warming service.  Then add the Amilla Fushi resort’s outstanding facilities:  restaurants, spa, personal training, kids club, diving, big game fishing and water sports, excursions, pro tennis, football and many other activities. This is “paradise, the most idyllic and relaxing place on earth”, says supermodel Kate Moss.  We agree!",
        rules: [],
        amenities: [
            "Air-con (Bedrooms)",
            "Oven/Hotplates",
            "TV (Local channels)",
            "DVD Player",
            "Landline Phone (Local Calls)",
            "Internet (WiFi)",
            "Book Selection",
            "Iron/Board",
            "Private Entrance",
            "Air-con",
            "DVD Library",
            "IDD (Extra)",
            "Massage Beds",
            "Printer (Extra)",
            "Fax (Extra)",
            "CD Library",
            "Mobile Phone (Local Calls)",
            "iPod",
            "Sauna (shared)",
            "Tennis Court (shared)",
            "Bicycles",
            "Carbon Monoxide Detector",
            "Jacuzzi",
            "Baby Cot",
            "High Chairs",
            "Smoke Detector",
            "Swimming Pool (Private)",
            "Car Parking",
            "Washing Machine",
            "Dish Washer",
            "Bed Linen",
            "Towels",
            "Toiletries",
            "Equipped Kitchen",
            "BBQ",
            "Wine Fridge",
            "Coffee Machine",
            "TV (Satellite/Cable)",
            "CD Player/Stereo System",
            "iPod Dock/Speakers",
            "Internet (Fixed)",
            "Electronic Games (Playstation)",
            "Table Tennis",
            "Gym (shared)",
            "Generator",
            "Safe",
            "Computer (Extra)",
            "Extra Bed (Roll away/mattress) (Extra)",
        ],
        location: "Amilla Fushi, Baa Atoll, Male, Republic of Maldives 2123",
        price: 563550,
        capacity: ["Upto 16 Guests", "8 Bedrooms", "8 Bathrooms", "1 Pool"],
        _tm: 132600,
        _lr: 530400,
        _hr: 596700,
        vendor: "Lohono Stays",
        guests: 16,
        bedrooms: 8,
        rating: "4.5",
        reveiws: 16367,
    },
    {
        name: "Amilla – The Villa Estate",
        url: "https://www.lohono.com/villas/maldives/maldives/amilla-the-amilla-villa-estate?adult_count=2",
        images: [
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/01-The_Amilla_Villa_Estate_-_Picture_perfect.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/02-The_Amilla_Villa_Estate_-_Luxuriate_poolside.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/03-The_Amilla_Villa_Estate_-_Phenominal_position.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/04-The_Amilla_Villa_Estate_-_Absolute_beachfront.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/05-The_Amilla_Villa_Estate_-_Absolute_beachfront_perfection.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/06-The_Amilla_Villa_Estate_-__Breathtaking_location.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/07-The_Amilla_Villa_Estate_-_Blue_beyond_blue_vista.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/08-The_Amilla_Villa_Estate_-_Endless_areas_for_entertaining.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/09-The_Amilla_Villa_Estate_-_Dine_in_style.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/10-The_Amilla_Villa_Estate_-_Laze_away_in_style.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/11-The_Amilla_Villa_Estate_-_Beach_umbrellas.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/12-The_Amilla_Villa_Estate_-_Magnificent_location.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/13-The_Amilla_Villa_Estate_-_Spectacular_diving_experience_with_Blue_Hole.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/14-The_Amilla_Villa_Estate_-_Tennis_for_everyone.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/15-The_Amilla_Villa_Estate_-_Exceptional_facilities.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/16-The_Amilla_Villa_Estate_-_Contemporary_beachfront_luxe.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/17-The_Amilla_Villa_Estate_-_Spectacular_outlook.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/18-The_Amilla_Villa_Estate_-_Private_roof_terrace.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/19-The_Amilla_Villa_Estate_-_Open_entertaining_spaces.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/20-The_Amilla_Villa_Estate_-_Pool_perfection.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/21-The_Amilla_Villa_Estate_-_The_perfect_setting.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/22-The_Amilla_Villa_Estate_-_Absolute_dream_location.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/23-The_Amilla_Villa_Estate_-_Tropical_paradise.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/24-The_Amilla_Villa_Estate_-_Clean_lines.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/25-The_Amilla_Villa_Estate_-_Luxury_awaits.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/26-The_Amilla_Villa_Estate_-_Pure_decadence.jpg",
            "https://d3oo9u3p09egds.cloudfront.net/filters:format(webp)/rental_property/amilla-the-amilla-villa-estate/27-The_Amilla_Villa_Estate_-_Pure_luxury.jpg",
        ],
        description:
            "The sensational 6-bedroom The Amilla Villa Estate is one of just eight private luxury residences on this coral-fringed tropical island resort in the Maldives’ Baa Atoll – a UNESCO biosphere reserve.  Think absolute beachfront location, crystal lagoons, pristine white sands, private pool, stellar living space, and personal spa, gym and games rooms.  Then add the ultra-chic Amilla Fushi resort’s outstanding facilities: restaurants, spa, personal training, kids club, diving, big game fishing and water sports, pro tennis, football and many other exciting activities.  This is “paradise, the most idyllic and relaxing place on earth”, says supermodel Kate Moss.  We agree!",
        rules: [],
        amenities: [
            "Oven/Hotplates",
            "TV (Local channels)",
            "DVD Player",
            "Landline Phone (Local Calls)",
            "Internet (WiFi)",
            "Book Selection",
            "Printer",
            "Computer",
            "Iron/Board",
            "Private Entrance",
            "Air-con",
            "DVD Library",
            "IDD (Extra)",
            "Massage Beds",
            "CD Library",
            "Mobile Phone (Local Calls)",
            "iPod",
            "Tennis Court (shared)",
            "Bicycles",
            "Carbon Monoxide Detector",
            "Sauna",
            "Fax",
            "Main Dining (14 persons)",
            "Jacuzzi",
            "High Chairs",
            "Extra Bed (Roll away/mattress) (Extra)",
            "Smoke Detector",
            "Ceiling Fans (Living Area)",
            "Swimming Pool (Private)",
            "Car Parking",
            "Washing Machine",
            "Dish Washer",
            "Bed Linen",
            "Towels",
            "Toiletries",
            "Equipped Kitchen",
            "Microwave",
            "BBQ",
            "Wine Fridge",
            "Coffee Machine",
            "TV (Satellite/Cable)",
            "CD Player/Stereo System",
            "iPod Dock/Speakers",
            "Internet (Fixed)",
            "Snooker/Pool Table",
            "Electronic Games (Playstation)",
            "Table Tennis",
            "Gym (shared)",
            "Safe",
            "Generator",
        ],
        location: "Amilla Fushi, Baa Atoll, Male, Republic of Maldives 2123",
        price: 671925,
        capacity: ["Upto 12 Guests", "6 Bedrooms", "6 Bathrooms", "1 Pool"],
        _tm: 158100,
        _lr: 632400,
        _hr: 711450,
        vendor: "Lohono Stays",
        guests: 12,
        bedrooms: 6,
        rating: "4.0",
        reveiws: 7140,
    },
];

export default villas;
